export const ReportLocalization = {
  reports: "گزارشات",
  deviceName: "نام دستگاه",
  hHumidity: "رطوبت ساعتی",
  hTemperature: "دما ساعتی",
  humidity: "رطوبت لحظه‌ای",
  temperature: "دما لحظه ای",
  hHumidityCart: "نمودار رطوبت ساعتی",
  hTemperatureCart: "نمودار دمای ساعتی",
  humidityChart: "نمودار رطوبت لحظه‌ای",
  temperatureCart: "نمودار دمای لحظه‌ای",
  hChart: "نمودار ساعتی",
  Chart: "نمودار لحظه‌ای",
  resetZoom: "بازنشانی زوم",
  periodDate: "انتخاب بازه زمانی",
  fromDate: "از تاریخ",
  toDate: "تا تاریخ",
  time: "زمان",
  value: "مقدار",
  error: "❌ خطا در گرفتن داده‌ها:",
};
